PLAYER_SUCCESSFULLY_REGISTERED = "PLAYER_SUCCESSFULLY_REGISTERED"
PAYMENT_SUCCESSFULLY_REGISTERED = "PAYMENT_SUCCESSFULLY_REGISTERED"

PLAYER_ALREADY_EXISTS = "PLAYER_ALREADY_EXISTS"
PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND"
NO_PAYMENTS_FOR_PLAYER = "NO_PAYMENTS_FOR_PLAYER"

NO_REGISTERED_PLAYERS = "NO_REGISTERED_PLAYERS"
NO_REGISTERED_PAYMENTS = "NO_REGISTERED_PAYMENTS"

PLAYER_ACTIVE = "PLAYER_ACTIVE"
PLAYER_INACTIVE = "PLAYER_INACTIVE"

INVALID_NUMBER_OF_MONTHS = "INVALID_NUMBER_OF_MONTHS"